site_name: My CCNP Workbook
pages:
    - Home: 'index.md'
    - Exam Topics: 'exam-topics.md'
    - 1. Layer 2 Technologies:
        - 1.1 Configure and verify switch administration: 'layer-2-technologies/switch-administration.md'
        - 1.2 Configure and verify Layer 2 protocols: 'layer-2-technologies/layer-2-protocols.md'
        - 1.3 Configure and verify VLANs: 'layer-2-technologies/vlans.md'
        - 1.4 Configure and verify trunking: 'layer-2-technologies/trunking.md'
        - 1.5 Configure and verify EtherChannels: 'layer-2-technologies/etherchannels.md'
        - 1.6 Configure and verify spanning tree: 'layer-2-technologies/spanning-tree.md'
        - 1.7 Configure and verify other LAN switching technologies: 'layer-2-technologies/other-technologies.md'
        - 1.8 Describe chassis virtualization and aggregation technologies: 'layer-2-technologies/chassis-virtualization.md'
    - About: 'about.md'
theme: readthedocs
